version: '2'

services:

  atsd:
    image: axibase/atsd:latest
    ports:
      - "8088:8088" 
      - "8443:8443" 
      - "8081:8081" 
      - "8082:8082/udp"
    container_name: atsd
    hostname: atsd
    environment:
      - ATSD_USER_NAME=axibase 
      - ATSD_USER_PASSWORD=******** 

  collector:
    image: axibase/collector:latest
    depends_on:
      - atsd
    ports:
      - "9443:9443"
    container_name: axibase-collector
    hostname: axibase-collector
    volumes:
      - /tmp/jobs:/tmp/jobs/docker.xml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - COLLECTOR_ARGS=-atsd-url=https://axibase:********@atsd:8443 -atsd-tcp-host=atsd -atsd-tcp-port=8081 -job-path=/tmp/jobs/docker.xml
